language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest
  - acasearch --query 'Attention is all you need' --num 5 --dry